name: superdeck_example
description: An example presentation for SuperDeck
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.6"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  ack: ^1.2.0
  ack_annotations: ^1.2.0
  google_fonts: ^8.1.0
  mesh: ^0.5.0
  mix: ^2.2.0-beta.0
  superdeck_core: ^1.0.0
  superdeck: ^1.0.0
  signals_flutter: ^7.1.0
  naked_ui: ^1.0.0-beta.4
  remix: ^1.0.0-beta.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  ack_generator: ^1.2.0
  superdeck_builder: ^1.0.0
  superdeck_cli: ^1.0.0
  superdeck_pdf: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .superdeck/
    - layout_showcase/assets/
    - layout_showcase/.superdeck/
